version: "3"
services:
  nlp:
    image: joeybones/stanford_corenlp
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: "0.50"
          memory: 10G
      restart_policy:
        condition: on-failure
    ports:
      - "9000:9000"
    networks:
      - webnet
  gendermeme:
    image: joeybones/gendermeme
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: "0.1"
          memory: 100M
      restart_policy:
        condition: on-failure
    environment:
      - CORENLP_HOSTNAME=nlp
      - CORENLP_PORT=9000
    ports:
      - "5000:5000"
    networks:
      - webnet
    links:
      - nlp
networks:
  webnet:
