apiVersion: apps/v1
kind: Deployment
metadata:
  name: gendermeme-deployment
spec:
  selector:
    matchLabels:
      app: gm-python
  replicas: 1
  template:
    metadata:
      labels:
        app: gm-python
        run: gendermeme
    spec:
      containers:
      - name: gm-python-container
        image: joeybones/gendermeme
        env:
        - name: CORENLP_HOSTNAME
          value: "gm-service"
        - name: CORENLP_PORT
          value: "80"
        - name: GENDERMEME_PORT
          value: "5000"
        ports:
        - containerPort: 5000
        livenessProbe:
          httpGet:
            path: /check
            port: 5000
          periodSeconds: 120
          initialDelaySeconds: 10
          timeoutSeconds: 15
        readinessProbe:
          httpGet:
            path: /check
            port: 5000
          periodSeconds: 120
          initialDelaySeconds: 10
          timeoutSeconds: 15
      nodeSelector:
        service-type: analysis

---
apiVersion: v1
kind: Service

metadata:
  name: gendermeme-frontend
  annotations:
    cloud.google.com/load-balancer-type: "Internal"

spec:
  type: LoadBalancer
  loadBalancerIP: 35.237.162.42
  selector:
    app: nlp
  ports:
    - name: http
      port: 80
      targetPort: 5000
      protocol: TCP
