apiVersion: apps/v1
kind: Deployment
metadata:
  name: nlp-deployment
spec:
  selector:
    matchLabels:
      app: nlp
  replicas: 1
  template:
    metadata:
      labels:
        app: nlp
        run: gendermeme
    spec:
      containers:
      - name: nlp-container
        image: joeybones/corenlp
        ports:
        - containerPort: 9000
        resources:
          requests:
            cpu: .5
            memory: 4G
          limits:
            cpu: 1.1
            memory: 8G
        livenessProbe:
          httpGet:
            path: /
            port: 9000
          periodSeconds: 120
          initialDelaySeconds: 10
          timeoutSeconds: 15
        readinessProbe:
          httpGet:
            path: /
            port: 9000
          periodSeconds: 120
          initialDelaySeconds: 10
          timeoutSeconds: 15
      nodeSelector:
        service-type: nlp

---
kind: Service
apiVersion: v1
metadata:
  name: gendermeme-service
spec:
  selector:
    app: nlp
  ports:
  - protocol: TCP
    port: 80
    targetPort: 9000